### PR TITLE
Fix compilation error caused by incompatible-pointer-types warning

### PR DESCRIPTION
**Pull request by skvalex**

### CODE REVIEW

**Comment by zhouziyang** [comment]
previously, `-W` compiler flags is added, but I think this is a bad practice, and should fix those warnings (especially in `dep.c`).
thanks anyway.
